# Generated by Django 5.2.11 on 2026-02-20 01:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('raw_text', models.TextField()),
                ('complexity_score', models.DecimalField(decimal_places=2, help_text='Complexidade calculada do texto (ex.: 0.00 a 99.99).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'text_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='idx_textdoc_title'), models.Index(fields=['complexity_score'], name='idx_textdoc_complexity')],
            },
        ),
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=128)),
                ('pos_tag', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('ADP', 'Adposition'), ('AUX', 'Auxiliary'), ('CCONJ', 'Coordinating Conjunction'), ('SCONJ', 'Subordinating Conjunction'), ('DET', 'Determiner'), ('INTJ', 'Interjection'), ('NUM', 'Numeral'), ('PART', 'Particle'), ('PROPN', 'Proper Noun'), ('PUNCT', 'Punctuation'), ('SYM', 'Symbol'), ('X', 'Other')], db_index=True, max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter'), ('X', 'Not Applicable')], db_index=True, default='X', max_length=1)),
            ],
            options={
                'db_table': 'word_tokens',
                'indexes': [models.Index(fields=['lemma'], name='idx_wordtoken_lemma'), models.Index(fields=['lemma', 'pos_tag'], name='idx_wordtoken_lemma_pos')],
                'constraints': [models.UniqueConstraint(fields=('lemma', 'pos_tag', 'gender'), name='uq_wordtoken_lemma_pos_gender')],
            },
        ),
        migrations.CreateModel(
            name='UserKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_level', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Nível de retenção para SRS (0 a 5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('next_review_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_knowledge', to=settings.AUTH_USER_MODEL)),
                ('word_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge', to='alemao_app.wordtoken')),
            ],
            options={
                'db_table': 'user_knowledge',
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='idx_uk_user_nextreview'), models.Index(fields=['user', 'retention_level'], name='idx_uk_user_retention'), models.Index(fields=['word_token', 'retention_level'], name='idx_uk_word_retention')],
                'constraints': [models.UniqueConstraint(fields=('user', 'word_token'), name='uq_userknowledge_user_wordtoken')],
            },
        ),
        migrations.CreateModel(
            name='TextTokenRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Posição do token no texto (base 0 ou 1, conforme convenção da aplicação).')),
                ('grammatical_case', models.CharField(choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv'), ('NONE', 'Not Applicable')], db_index=True, default='NONE', max_length=4)),
                ('text_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_relations', to='alemao_app.textdocument')),
                ('word_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_relations', to='alemao_app.wordtoken')),
            ],
            options={
                'db_table': 'text_token_relations',
                'indexes': [models.Index(fields=['text_document', 'position'], name='idx_ttr_doc_pos'), models.Index(fields=['text_document', 'word_token'], name='idx_ttr_doc_word'), models.Index(fields=['word_token', 'grammatical_case'], name='idx_ttr_word_case')],
                'constraints': [models.UniqueConstraint(fields=('text_document', 'position'), name='uq_texttokenrelation_doc_position')],
            },
        ),
    ]
