# Generated by Django 5.2.11 on 2026-02-20 03:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemao_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_scenarios',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='idx_cs_active')],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('previous_retention_level', models.PositiveSmallIntegerField()),
                ('new_retention_level', models.PositiveSmallIntegerField()),
                ('previous_next_review_at', models.DateTimeField()),
                ('new_next_review_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to=settings.AUTH_USER_MODEL)),
                ('user_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='alemao_app.userknowledge')),
            ],
            options={
                'db_table': 'review_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_re_user_created'), models.Index(fields=['score', 'created_at'], name='idx_re_score_created')],
            },
        ),
        migrations.CreateModel(
            name='TranslationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_pt', models.TextField()),
                ('attempt_de', models.TextField()),
                ('context_original', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('feedback', models.TextField(blank=True, default='')),
                ('suggested_de', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'translation_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_ta_user_created'), models.Index(fields=['is_correct', 'created_at'], name='idx_ta_correct_created')],
            },
        ),
        migrations.CreateModel(
            name='WordClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_click_events', to='alemao_app.textdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_click_events', to=settings.AUTH_USER_MODEL)),
                ('word_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='alemao_app.wordtoken')),
            ],
            options={
                'db_table': 'word_click_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_wce_user_created'), models.Index(fields=['word_token', 'created_at'], name='idx_wce_word_created')],
            },
        ),
    ]
