# Generated by Django 5.2.11 on 2026-02-20 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alemao_app', '0002_clinicalscenario_reviewevent_translationattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1')], db_index=True, default='B1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='clinicalscenario',
            name='proficiency_level',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1')], db_index=True, default='C1', max_length=2),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicalscenario',
            index=models.Index(fields=['proficiency_level', 'is_active'], name='idx_cs_level_active'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['proficiency_level'], name='idx_up_level'),
        ),
    ]
