C1_SCENARIOS = [
    "Aufgrund des progredienten Lungenversagens und der refraktären Hypoxämie müssen wir den Patienten umgehend an die veno-venöse ECMO anschließen.",
    "Trotz maximaler konservativer Therapie mittels Katecholaminen bleibt der mittlere arterielle Druck infolge des septischen Schocks kritisch niedrig.",
    "Angesichts der massiven intrazerebralen Blutung mit Mittellinienverlagerung ist eine sofortige neurochirurgische Entlastungstrepanation unabdingbar.",
    "Die Patientin, deren Zustand sich nach der präklinischen Intubation kurzzeitig stabilisiert hatte, entwickelte plötzlich einen Spannungspneumothorax, der eine sofortige Thoraxdrainage erforderte.",
    "Infolge der schweren Rauchgasintoxikation und des resultierenden Inhalationstraumas müssen wir die Atemwege frühzeitig sichern, bevor das Larynxödem fortschreitet.",
    "Hinsichtlich der ausgeprägten Rhabdomyolyse nach dem Verschüttungstrauma ist eine forcierte Diurese essentiell, um ein akutes Nierenversagen abzuwenden.",
    "Bezüglich der unklaren abdominellen Abwehrspannung bei dem wachen, aber tachykarden Patienten veranlassen wir ein biphasisches CT-Abdomen im Schockraum.",
    "Nachdem der Patient über vernichtende, in den Rücken ausstrahlende Thoraxschmerzen geklagt hatte, bestätigte das Angio-CT die Diagnose einer Typ-A-Aortendissektion.",
    "Während der Notarzt noch die Reanimationsmaßnahmen leitete, bereitete das Schockraumteam bereits die massive Transfusion über den Level-1-Infuser vor.",
    "Obwohl die Ersthelfer sofort mit der Herzdruckmassage begonnen hatten, zeigte das initiale EKG ein Kammerflimmern, das erst nach dem dritten Schock konvertierte.",
    "Damit wir den intrakraniellen Druck senken können, applizieren wir hochprozentige hypertone Kochsalzlösung und positionieren den Oberkörper um 30 Grad erhöht.",
    "Der verunfallte Motorradfahrer, dem wir präklinisch bereits zwei großlumige Zugänge gelegt haben, blutet weiterhin stark aus der offenen Oberschenkelfraktur.",
    "Aufgrund der fulminanten Lungenembolie mit konsekutiver Rechtsherzbelastung diskutieren wir interdisziplinär den Einsatz einer systemischen Lysetherapie.",
    "Trotz der sofortigen Gabe von Adrenalin intramuskulär zeigte der Patient mit anaphylaktischem Schock weiterhin einen bedrohlichen inspiratorischen Stridor.",
    "Angesichts des persistierenden Status epilepticus verabreichen wir Levetiracetam intravenös, nachdem die Benzodiazepine keine ausreichende Wirkung zeigten.",
    "Infolge des schweren stumpfen Thoraxtraumas kam es zu einer Lungenkontusion, die nun im Verlauf auf der Intensivstation zu einer massiven Oxygenierungsstörung führt.",
    "Hinsichtlich der komplexen Beckenringfraktur mit hämodynamischer Instabilität legen wir dem Patienten noch im Schockraum eine Beckenzwinge an.",
    "Bezüglich der akuten gastrointestinalen Blutung bei bekannter Leberzirrhose fordern wir umgehend die Notfallendoskopie und vier Erythrozytenkonzentrate an.",
    "Nachdem die kardiopulmonale Reanimation erfolgreich war, leiten wir das Post-Resuscitation-Care-Protokoll inklusive gezieltem Temperaturmanagement ein.",
    "Während der Anlage des zentralen Venenkatheters unter Ultraschallkontrolle kam es zu einer passageren Arrhythmie, die sich glücklicherweise spontan limitierte.",
    "Obwohl der Patient präklinisch analgosediert wurde, wehrt er bei der Untersuchung des Abdomens stark ab, was eindeutig auf eine Peritonitis hindeutet.",
    "Damit die Oxygenierung bei dem stark adipösen Patienten gewährleistet bleibt, intubieren wir videolaryngoskopisch in leicht aufgerichteter Position.",
    "Die Schwangere im dritten Trimenon, die nach dem Verkehrsunfall über Unterleibsschmerzen klagt, wird umgehend zur sonographischen Ausschlussdiagnostik einer Plazentaablösung gebracht.",
    "Aufgrund des progredienten kardiogenen Schocks bei akutem Vorderwandinfarkt indiziert der Oberarzt die Anlage einer intraaortalen Ballonpumpe.",
    "Trotz der raschen chirurgischen Blutstillung entwickelt der polytraumatisierte Patient eine letale Triade aus Hypothermie, Azidose und Koagulopathie.",
    "Angesichts der schweren Verätzung des Gastrointestinaltrakts ist eine blinde Magenspülung absolut kontraindiziert, weshalb wir primär endoskopieren.",
    "Infolge der prolongierten Hypoxie während des Ertrinkungsunfalls im kalten See müssen wir mit einem schweren hypoxischen Hirnschaden rechnen.",
    "Hinsichtlich der offenen Unterschenkelfraktur mit starker Verschmutzung ist eine intravenöse Antibiose sowie eine chirurgische Wundrevision obligat.",
    "Bezüglich des Verdachts auf eine fulminante bakterielle Meningitis führen wir eine Lumbalpunktion durch, noch bevor das erste Antibiotikum verabreicht wird.",
    "Nachdem der Patient extubiert wurde, entwickelte er einen ausgeprägten Laryngospasmus, der eine erneute Maskenbeatmung mit positivem endexspiratorischem Druck erforderte.",
    "Nachdem der intubierte Patient auf die Intensivstation verlegt worden war, verschlechterte sich die Oxygenierung zunehmend, weshalb eine Bauchlagerung indiziert schien.",
    "Trotz der umgehend eingeleiteten Lysetherapie bildete sich die Hemiparese nicht zurück, was auf ein ausgedehntes Infarktareal im Bereich der Arteria cerebri media hindeutete.",
    "Aufgrund der rezidivierenden ventrikulären Tachykardien, die auf Amiodaron nicht ansprachen, entschied sich das Team für eine elektrische Kardioversion.",
    "Während der Notaufnahme klagte die Patientin über einen vernichtenden Kopfschmerz, der typischerweise einer Subarachnoidalblutung vorausgeht.",
    "Infolge der langjährigen, schlecht eingestellten arteriellen Hypertonie wies das Echokardiogramm eine deutliche linksventrikuläre Hypertrophie auf.",
    "Bevor wir den zentralen Venenkatheter entfernen konnten, musste sichergestellt werden, dass die Gerinnungsparameter des Patienten im Normbereich lagen.",
    "Angesichts der instabilen Beckenringfraktur, die mit einem massiven retroperitonealen Hämatom einherging, wurde umgehend eine Beckenzwinge angelegt.",
    "Obwohl die Laborwerte anfangs unauffällig erschienen, stieg das CRP im weiteren Verlauf drastisch an, was den Verdacht auf eine beginnende Sepsis erhärtete.",
    "Die junge Frau, die infolge einer schweren allergischen Reaktion einen anaphylaktischen Schock erlitt, reagierte prompt auf die intramuskuläre Adrenalingabe.",
    "Wegen der drohenden Einklemmung bei progredientem Hirnödem verabreichten wir hochprozentige hypertone Kochsalzlösung und hoben den Oberkörper an.",
    "Der Chirurg, dem die komplexe Frakturversorgung oblag, forderte zusätzliches Osteosynthesematerial aus dem Sterillager an.",
    "Sobald die hämodynamische Stabilität wiederhergestellt ist, planen wir die Durchführung eines Ganzkörper-CTs, um weitere okkulte Verletzungen auszuschließen.",
    "Anstelle einer offenen Laparotomie versuchte man zunächst, die intraabdominelle Blutung minimalinvasiv zu stillen, was jedoch misslang.",
    "Da der Patient anamnestisch über rezidivierende Synkopen berichtete, ordneten wir ein Langzeit-EKG sowie eine Kipptischuntersuchung an.",
    "Hinsichtlich des erhöhten Risikos für thromboembolische Ereignisse wurde bei der bettlägerigen Patientin eine niedermolekulare Heparinisierung begonnen.",
    "Der aufnehmende Arzt dokumentierte im Statusblatt, dass das Abdomen bretthart war und die Darmgeräusche vollständig fehlten.",
    "Die im Rahmen der Reanimation verabreichten Katecholamine führten zu einer deutlichen peripheren Vasokonstriktion, die die Pulsoxymetrie erschwerte.",
    "Im Gegensatz zu der initial vermuteten Exazerbation der COPD zeigte das Röntgen-Thorax-Bild ein ausgedehntes Lobärpneumonie-Infiltrat rechts basal.",
    "Entsprechend der aktuellen Leitlinien leiteten wir beim akuten Koronarsyndrom sofort eine duale Plättchenhemmung sowie eine Vollheparinisierung ein.",
    "Der schwer brandverletzte Patient, dessen Atemwege durch das Inhalationstrauma rasch zuschwollen, musste noch am Unfallort fiberoptisch intubiert werden.",
    "Bezüglich der unklaren Raumforderung im linken Lungenunterlappen empfahl das Tumorboard eine zeitnahe bronchoskopische Biopsie.",
    "Solange der intrakranielle Druck nicht verlässlich gemonitort werden kann, verzichten wir auf eine tiefe Analgosedierung, um die Pupillenfunktion beurteilen zu können.",
    "Die Kollegin aus der Anästhesie bemerkte einen plötzlichen Abfall des endtidalen CO2, woraufhin sofort die Lage des Tubus überprüft wurde.",
    "Ein stark blutendes Ulcus ventriculi, das endoskopisch nicht suffizient versorgt werden konnte, machte eine notfallmäßige chirurgische Intervention erforderlich.",
    "Neben der adäquaten Schmerztherapie erfordert die akute Pankreatitis eine aggressive Volumensubstitution, da der Flüssigkeitsverlust in den dritten Raum beträchtlich ist.",
    "Der diensthabende Neurologe bestätigte den Verdacht auf einen Status epilepticus, den wir schließlich mit einer kontinuierlichen Propofol-Infusion durchbrechen mussten.",
    "Bevor der Rettungshubschrauber abheben konnte, musste der Kreislauf des polytraumatisierten Kindes durch die Anlage eines intraossären Zugangs stabilisiert werden.",
    "Die schwangere Patientin, bei der sich plötzlich eine Eklampsie entwickelte, wurde unter Magnesiumschutz umgehend in den Kreißsaal verlegt.",
    "Um einer progredienten respiratorischen Erschöpfung vorzubeugen, schlossen wir den Patienten an eine nicht-invasive Beatmung (NIV) an.",
    "Nachdem der toxikologische Befund eine lebensbedrohliche Digoxin-Intoxikation bestätigt hatte, applizierten wir unverzüglich das spezifische Antidot.",
    "Ich bitte Sie, unverzüglich das Herzkatheterlabor zu verständigen, da das aktuelle EKG zweifelsfrei einen inferioren STEMI zeigt.",
    "Hätten Sie die Freundlichkeit, dem Patienten im Schockraum bereits einen großlumigen Zugang zu legen und Blut für die Kreuzprobe abzunehmen?",
    "Laut Übergabeprotokoll des Rettungsdienstes wurde präklinisch bereits Amiodaron appliziert, weshalb wir nun streng auf eine mögliche Bradykardie achten müssen.",
    "Könnten Sie bitte überprüfen, ob die angeforderten Erythrozytenkonzentrate bereits auf der Station eingetroffen sind? Der Hb-Abfall ist bedrohlich.",
    "Es ist unabdingbar, dass bei diesem isolierungspflichtigen Patienten mit Verdacht auf offene Tuberkulose strenge Hygienemaßnahmen eingehalten werden.",
    "Ziehen Sie bitte den diensthabenden Chirurgen konsiliarisch hinzu, da das akute Abdomen auf unsere konservative Therapie nicht anspricht.",
    "Ich möchte, dass Sie den Perfusor mit Noradrenalin sofort aufziehen, falls der mittlere arterielle Druck unter 65 mmHg abfällt.",
    "Bereiten Sie bitte alles für eine Pleurapunktion vor; der ausgedehnte Pleuraerguss rechtsseitig kompromittiert die Atmung des Patienten erheblich.",
    "Sobald die Laborergebnisse bezüglich des Troponin-T-Wertes vorliegen, informieren Sie mich bitte umgehend auf dem Diensttelefon.",
    "Wir müssen die Sedierungstiefe reduzieren, um eine aussagekräftige neurologische Beurteilung mittels Glasgow Coma Scale durchführen zu können.",
    "Herr Oberarzt, angesichts der progredienten Niereninsuffizienz hielte ich es für sinnvoll, die nephrotoxische Antibiose umzustellen, würden Sie dem zustimmen?",
    "Trotz maximaler Beatmungstherapie bleibt der Patient hypoxisch; meines Erachtens sollten wir die Indikation für eine veno-venöse ECMO evaluieren.",
    "Ich habe Rücksprache mit der Radiologie gehalten, und man rät uns von einer Kontrastmittelgabe ab, da die GFR des Patienten grenzwertig ist.",
    "Meiner Einschätzung nach handelt es sich hierbei nicht um eine einfache Synkope, sondern vielmehr um ein beginnendes kardiogenes Schockgeschehen.",
    "Wären Sie einverstanden, wenn wir den Patienten extubieren und einen Versuch mit High-Flow-Sauerstofftherapie wagen, bevor wir eine Tracheotomie in Erwägung ziehen?",
    "Die interdisziplinäre Fallbesprechung hat ergeben, dass ein palliativer Ansatz zugunsten der Lebensqualität des Patienten in den Vordergrund rücken sollte.",
    "Ich bezweifle, dass die aktuelle Dosierung des Heparins ausreicht, um bei dieser massiven Lungenembolie eine adäquate Antikoagulation zu gewährleisten.",
    "Lassen Sie uns das Vorgehen noch einmal rekapitulieren: Falls der Schrittmacher ausfällt, beginnen wir sofort mit der externen transkutanen Stimulation.",
    "Es steht außer Frage, dass die notfallmäßige Thorakotomie im Schockraum seine einzige Überlebenschance war, auch wenn die Prognose infaust bleibt.",
    "Wir sollten in Erwägung ziehen, die Kortisontherapie auszuschleichen, da die Gefahr einer steroidinduzierten Psychose bei diesem Patienten nicht zu unterschätzen ist.",
    "Es tut mir aufrichtig leid, Ihnen mitteilen zu müssen, dass Ihr Ehemann trotz all unserer Reanimationsbemühungen an den Folgen des schweren Herzinfarkts verstorben ist.",
    "Wir haben den Zustand Ihrer Mutter vorerst stabilisieren können, allerdings bleibt die Situation in den kommenden 48 Stunden äußerst kritisch.",
    "Ich verstehe Ihre Sorge vollkommen, aber ohne eine rechtliche Betreuungsverfügung dürfen wir Sie über detaillierte Behandlungsabläufe leider nicht aufklären.",
    "Aufgrund der akuten Eigen- und Fremdgefährdung im Rahmen der psychotischen Episode mussten wir eine fürsorgerische Unterbringung in der geschlossenen Psychiatrie veranlassen.",
    "Leider hat das Schädel-Hirn-Trauma zu irreversiblen Schäden geführt; wir müssen nun gemeinsam darüber sprechen, welche lebenserhaltenden Maßnahmen noch in seinem Sinne wären.",
    "Der Patient lehnt die lebensrettende Bluttransfusion aus religiösen Gründen strikt ab, was wir als Ärzte, solange er urteilsfähig ist, rechtlich respektieren müssen.",
    "Bitte nehmen Sie Platz; wir müssen Ihnen die Ergebnisse des aktuellen MRTs erläutern, die leider nicht die erhoffte Besserung des Tumorleidens zeigen.",
    "Es ist von größter Wichtigkeit, dass Sie uns über alle Medikamente informieren, die Ihre Frau regelmäßig einnimmt, insbesondere über Blutverdünner.",
    "Wir tun momentan alles medizinisch Mögliche, um seine Schmerzen zu lindern und ihm das Atmen zu erleichtern, was in dieser palliativen Phase unser oberstes Ziel ist.",
    "Die Entscheidung, die Reanimation nach 45 Minuten erfolgloser Bemühungen abzubrechen, ist uns nicht leichtgefallen, war aber aus medizinischer Sicht unumgänglich.",
]
